# Generated by Django 5.0.7 on 2024-07-15 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('prenom', models.CharField(max_length=30)),
                ('telephone', models.CharField(max_length=15)),
                ('role', models.CharField(choices=[('coach', 'Coach'), ('client', 'Client')], max_length=10)),
                ('password', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.user')),
                ('age', models.IntegerField()),
                ('poids', models.FloatField()),
                ('objectifs', models.TextField()),
                ('taille', models.FloatField()),
                ('niveau', models.CharField(max_length=30)),
            ],
            bases=('users.user',),
        ),
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.user')),
                ('specialite', models.CharField(max_length=50)),
                ('review', models.IntegerField(default=0)),
            ],
            bases=('users.user',),
        ),
    ]
