# Generated by Django 5.0.7 on 2024-08-15 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0003_remove_programs_client_alter_programs_duree'),
        ('users', '0002_user_email_user_groups_user_is_superuser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='programmes',
            field=models.ManyToManyField(blank=True, related_name='clients', to='programs.programs'),
        ),
    ]
