# Generated by Django 5.0.7 on 2024-09-12 17:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_client_programmes'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='date_creation',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
