# Generated by Django 5.0.7 on 2024-07-31 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0001_initial'),
        ('users', '0002_user_email_user_groups_user_is_superuser_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Progression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('note', models.IntegerField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progressions', to='users.client')),
                ('exercice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progressions', to='exercises.exercice')),
            ],
        ),
        migrations.DeleteModel(
            name='Porteuse',
        ),
    ]
