# Generated by Django 5.0.7 on 2024-08-02 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0002_progression_delete_porteuse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercice',
            name='duree',
            field=models.CharField(),
        ),
    ]
