# Generated by Django 5.0.7 on 2024-08-13 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0003_alter_exercice_duree'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercice',
            name='File',
            field=models.CharField(default='default.txt', max_length=200),
        ),
    ]
