# Generated by Django 5.0.7 on 2024-08-13 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0004_exercice_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercice',
            name='File',
        ),
        migrations.AddField(
            model_name='exercice',
            name='file',
            field=models.CharField(default='default', max_length=200),
        ),
    ]
