# Generated by Django 5.0.7 on 2024-08-15 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0005_remove_exercice_file_exercice_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercice',
            name='file',
            field=models.CharField(max_length=200),
        ),
    ]
