# Generated by Django 5.0.7 on 2024-09-17 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0006_alter_exercice_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='progression',
            name='status',
            field=models.CharField(choices=[('ATTEINT', 'Objectif Atteint'), ('EN_COURS', 'En Progression'), ('NON_ATTEINT', 'Objectif Non Atteint')], default='En Progression', max_length=20),
            preserve_default=False,
        ),
    ]
