# Generated by Django 5.0.7 on 2024-07-15 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Programs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('duree', models.IntegerField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programmes', to='users.client')),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programmes', to='users.coach')),
            ],
        ),
    ]
