# Generated by Django 5.0.7 on 2024-07-31 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programs',
            name='duree',
            field=models.CharField(),
        ),
    ]
