# Generated by Django 5.0.7 on 2024-08-15 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0002_alter_programs_duree'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programs',
            name='client',
        ),
        migrations.AlterField(
            model_name='programs',
            name='duree',
            field=models.CharField(max_length=50),
        ),
    ]
